[[headers]]
  for = "/*.webp"
  [headers.values]
  cache-control = '''
  public,
  max-age=31556952,
  immutable'''
  
  for = "/*.jpg"
  [headers.values]
  cache-control = '''
  public,
  max-age=31556952,
  immutable'''

  for = "/*.png"
  [headers.values]
  cache-control = '''
  public,
  max-age=31556952,
  immutable'''
  
  for = "/*.svg"
  [headers.values]
  cache-control = '''
  public,
  max-age=31556952,
  immutable'''
