backend:
  auth_endpoint: /api/auth
  base_url: https://wfgmodular.pages.dev/
  branch: main
  name: github
  preview_context: cloudflare preview deploy
  repo: dindinet/wfgbuilder
  show_preview_links: true
  squash_merges: true
collections:
- create: true
  fields:
  - label: ID
    name: id
    widget: string
  - label: Link
    name: link
    required: false
    widget: string
  - label: First Name
    name: first_name
    widget: string
  - label: Last Name
    name: last_name
    widget: string
  - label: Photo
    name: photo
    required: false
    widget: image
  - label: Photo Alt
    name: photo_alt
    required: false
    widget: string
  - label: Bio
    name: bio
    required: false
    widget: markdown
  folder: data/team
  format: json
  label: 'Authors - Team Members'
  name: authors
  slug: '{{id}}'
- create: true
  fields:
  - label: ID
    name: id
    widget: string
  - label: Link
    name: link
    required: false
    widget: string
  - label: Title
    name: title
    widget: string
  folder: data/categories
  format: json
  label: Categories
  name: categories
  slug: '{{id}}'
- files:
  - fields:
    - label: Title
      name: title
      widget: string
    - default: page
      label: Layout
      name: layout
      widget: hidden
    - label: Body
      name: body
      widget: markdown
    file: content/about.md
    label: About Page
    name: about
  - fields:
    - label: Title
      name: title
      widget: string
    - default: page
      label: Layout
      name: layout
      widget: hidden
    - label: Body
      name: body
      widget: markdown
    file: content/style-guide.md
    label: Style Guide
    name: style-guide
  - fields:
    - label: Title
      name: title
      widget: string
    - default: page
      label: Layout
      name: layout
      widget: hidden
    - label: Body
      name: body
      widget: markdown
    file: content/features.md
    label: Features Page
    name: features
  - fields:
    - label: Title
      name: title
      widget: string
    - default: page
      label: Layout
      name: layout
      widget: hidden
    - label: Body
      name: body
      widget: markdown
    file: content/contact.md
    label: Contact Page
    name: contact
  - fields:
    - label: Title
      name: title
      widget: string
    - default: page
      label: Layout
      name: layout
      widget: hidden
    - label: Body
      name: body
      widget: markdown
    file: content/terms.md
    label: Terms Page
    name: terms
  label: Pages
  name: pages
- create: true
  fields:
  - label: Title
    name: title
    widget: string
  - default: post
    label: Layout
    name: layout
    widget: hidden
  - label: Date
    name: date
    widget: datetime
  - collection: authors
    display_fields:
    - first_name
    - last_name
    label: Author
    name: author
    search_fields:
    - first_name
    - last_name
    value_field: id
    widget: relation
  - collection: categories
    display_fields:
    - title
    label: Categories
    multiple: true
    name: categories
    search_fields:
    - title
    value_field: id
    widget: relation
  - label: Featured Image
    name: image
    widget: image
  - label: Image Alt
    name: image_alt
    widget: string
  - label: Excerpt
    name: excerpt
    widget: text
  - label: Body
    name: body
    widget: markdown
  - fields:
    - label: Title
      name: title
      widget: string
    - label: Description
      name: description
      widget: string
    - fields:
      - label: Name
        name: name
        widget: string
      - label: Value
        name: value
        widget: string
      - label: Key Name
        name: keyName
        widget: string
      - default: false
        label: Relative URL
        name: relativeUrl
        widget: boolean
      label: Extra
      name: extra
      required: false
      widget: list
    label: SEO
    name: seo
    widget: object
  folder: content/news
  label: Blog Posts
  name: posts
  preview_path: news/{{slug}}
  slug: '{{slug}}'
- create: true
  fields:
  - label: Title
    name: title
    widget: string
  - default: advanced
    label: Layout
    name: layout
    widget: hidden
  - default: []
    label: Page Sections
    name: sections
    types:
    - fields:
      - label: Title
        name: title
        required: false
        widget: string
      - label: Subtitle
        name: subtitle
        required: false
        widget: string
      - default:
        - narrow
        label: Width of section on page
        name: width
        options:
        - full
        - extra-wide
        - wide
        - narrow
        required: true
        widget: select
      - buttons:
        - bold
        - italic
        - link
        - heading-one
        - heading-two
        - heading-three
        - quote
        - bulleted-list
        - numbered-list
        label: Content
        name: content
        widget: markdown
      label: (WFG) General Content
      name: ContentSection
      summary: '{{fields.title}}-{{fields.subtitle}}'
      widget: object
    - fields:
      - label: Description(CMS)
        name: description
        required: true
        widget: string
      - default:
        - flush
        label: Width of section on page
        name: width
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      - buttons:
        - bold
        - italic
        - link
        - heading-one
        - heading-two
        - heading-three
        - quote
        - bulleted-list
        - numbered-list
        label: Content
        name: content
        widget: markdown
      label: (WFG) Centered Column
      name: FullWidthCenteredColumnSection
      summary: '{{fields.description}}'
      widget: object
    - fields:
      - label: Description(CMS)
        name: description
        required: true
        widget: string
      - label: Image
        name: image
        widget: image
      - label: Image alt text
        name: image_alt
        widget: string
      - label: Image Caption
        name: caption
        required: false
        widget: string
      label: Full Width Image Section
      name: FullWidthImageSection
      summary: '{{fields.description}} : {{fields.image_alt}}'
      widget: object
    - fields:
      - label: Description(CMS)
        name: description
        required: true
        widget: string
      - label: Image
        name: image
        required: true
        widget: image
      - default:
        - full
        label: Image Width
        name: width
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      - label: Image Alt Text
        name: image_alt
        required: false
        widget: string
      - label: Image Position
        name: imageposition
        options:
        - left
        - right
        widget: select
      - buttons:
        - bold
        - italic
        - link
        - heading-two
        - heading-three
        - quote
        - bulleted-list
        - numbered-list
        label: Content
        name: content
        widget: markdown
      label: Centered Content with a Full Bleed Image
      name: FullWidthSplitScreenSection
      summary: '{{fields.description}} : {{fields.image_alt}}'
      widget: object
    - fields:
      - default: flush
        label: Width
        name: width
        options:
        - narrow
        - wide
        - extra-wide
        - full
        - flush
        widget: select
      - label: Offer Text
        name: offertext
        widget: string
      - label: Offer Text Size
        name: offertextsize
        options:
        - '4'
        - '6'
        - '8'
        - '10'
        - '12'
        - '14'
        - '16'
        widget: select
      - default: '#000000'
        label: Offer Text Color
        name: offertextcolor
        widget: color
      - default: '#000000'
        label: Offer Text Outline Color
        name: offertextoutlinecolor
        widget: color
      - label: Top Secondary text
        name: tagline
        widget: string
      - label: Bottom Secondary Text
        name: description
        widget: string
      - label: Secondary Text Size
        name: taglinetextsize
        options:
        - '3'
        - '4'
        - '5'
        - '6'
        widget: select
      - default: '#000000'
        label: Secondary Text Color
        name: taglinetextcolor
        widget: color
      - label: Background Color
        name: bgcolor
        widget: color
      - label: Background Image
        name: bgimage
        required: false
        widget: image
      - fields:
        - label: Text
          name: text
          widget: string
        - label: Text Color
          name: textcolor
          widget: color
        - label: Background Color
          name: bgcolor
          widget: color
        - label: Action Target
          name: target
          widget: string
        label: Actions
        name: actions
        widget: list
      label: (WFG) Simple CTA
      name: SimpleCTA
      summary: '{{fields.offertext}} - {{fields.tagline}}'
      widget: object
    - fields:
      - label: Title
        name: title
        required: false
        widget: string
      - label: Subtitle
        name: subtitle
        required: false
        widget: string
      - label: Scroller Name
        name: scrollername
        required: true
        widget: string
      - default:
        - full
        label: Width of Slider on page
        name: scrollerwidth
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      - default: 1
        label: No of images to display
        max: 20
        min: 1
        name: visibleslides
        step: 1
        widget: number
      - default: 1
        label: No of images to scroll
        max: 20
        min: 1
        name: scrollby
        step: 1
        widget: number
      - label: Control Arrows color
        name: arrowcolor
        required: false
        widget: color
      - label: Control Arrows hover color
        name: arrowhovercolor
        required: false
        widget: color
      - label: Control Arrows position
        name: arrowsposition
        options:
        - label: Left and right of slides
          value: sides
        - label: Below slides
          value: below
        widget: select
      - label: Control Arrows position inside or outside the slide
        name: arrowinout
        options:
        - label: Inside the slide
          value: in
        - label: Outside the slide
          value: out
        widget: select
      - default: true
        label: Display pager
        name: displaypager
        widget: boolean
      - default: 5
        label: Portion of next slide visible
        max: 50
        min: 5
        name: nextvisible
        step: 5
        widget: number
      - fields:
        - label: Image
          name: scrollerimage
          widget: image
        - label: Image Alt text
          name: scrollerimagealt
          required: false
          widget: string
        label: Scroller Images
        name: scrollerimages
        widget: list
      label: (WFG) Image Slider
      name: SliderSection
      summary: 'Image Slider {{fields.title}} - {{fields.subtitle}}'
      widget: object
    - fields:
      - default: Meet Our Team
        label: Heading
        name: heading
        widget: string
      - label: Intro Text
        name: intro_text
        required: false
        widget: text
      - fields:
        - label: Image
          name: image
          widget: image
        - label: Name
          name: name
          widget: string
        - label: Title
          name: title
          widget: string
        - label: Bio
          name: bio
          widget: text
        label: Team Members
        name: team_members
        widget: list
      label: Team Roster Section
      name: TeamRosterSection
      widget: object
    - fields:
      - label: Title
        name: title
        required: false
        widget: string
      - collection: authors
        display_fields:
        - id
        label: Team Members
        multiple: true
        name: team
        search_fields:
        - id
        - first_name
        - last_name
        value_field: '{{slug}}'
        widget: relation
      - default:
        - wide
        label: Width of section on page
        name: width
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      label: Team Section
      name: TeamSection
      summary: '{{fields.title}}'
      widget: object
    - fields:
      - label: Title
        name: title
        required: false
        widget: string
      - default: true
        label: Show Recent
        name: show_recent
        widget: boolean
      - default: 10000
        label: Recent Count
        name: recent_count
        value_type: int
        widget: number
      - default:
        - wide
        label: Width of section on page
        name: width
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      label: (WFG) Blog Feed
      name: BlogFeedSection
      widget: object
    - fields:
      - default:
        - wide
        label: Width of section on page
        name: width
        options:
        - full
        - extra-wide
        - wide
        - flush
        required: true
        widget: select
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - fields:
        - label: Label
          name: label
          widget: string
        - label: URL
          name: url
          widget: string
        - label: Style
          name: style
          options:
          - primary
          - secondary
          widget: select
        label: Actions
        name: actions
        widget: list
      - default: false
        label: Has Background
        name: has_background
        widget: boolean
      - label: Background Color
        name: background_color
        widget: string
      label: CTA
      name: CtaSection
      summary: 'CTA - {{fields.title}}'
      widget: object
    - fields:
      - label: Title
        name: title
        widget: string
      - fields:
        - label: Title
          name: title
          widget: string
        - label: Content
          name: content
          widget: markdown
        - label: Image
          name: image
          widget: image
        - label: Image Alt
          name: image_alt
          widget: string
        - label: Image Position
          name: image_position
          options:
          - left
          - right
          widget: select
        - label: Align
          name: align
          options:
          - left
          - center
          - right
          widget: select
        - fields:
          - label: Label
            name: label
            widget: string
          - label: URL
            name: url
            widget: string
          - label: Style
            name: style
            options:
            - primary
            - secondary
            widget: select
          label: Actions
          name: actions
          widget: list
        label: Features
        name: features
        widget: list
      label: Features Section
      name: FeaturesSection
      summary: 'FEATURE - {{fields.title}}'
      widget: object
    - fields:
      - label: Title
        name: title
        widget: string
      - allowInput: true
        enableAlpha: true
        label: Title Colour
        name: titlecolour
        required: false
        widget: color
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Subtitle position
        name: subtitleposition
        options:
        - above
        - below
        widget: select
      - allowInput: true
        enableAlpha: true
        label: Subtitle Colour
        name: subtitlecolour
        required: false
        widget: color
      label: Full Width Heading Section
      name: FullWidthHeadingSection
      summary: '{{fields.title}} - {{fields.subtitle}}'
      widget: object
    - fields:
      - label: Title
        name: title
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Image
        name: bgimage
        widget: image
      - label: Image Alt
        name: bgimage_alt
        widget: string
      - fields:
        - label: Label
          name: label
          widget: string
        - label: URL
          name: url
          widget: string
        - label: Style
          name: style
          options:
          - primary
          - secondary
          widget: select
        label: Actions
        name: actions
        widget: list
      label: (WFG) Grid Hero
      name: GridHeroSection
      summary: '{{fields.title}} - {{fields.subtitle}}'
      widget: object
    - fields:
      - label: Title
        name: title
        widget: string
      - allowInput: true
        enableAlpha: true
        label: Title Color
        name: titlecolor
        required: false
        widget: color
      - label: Subtitle
        name: subtitle
        widget: string
      - allowInput: true
        enableAlpha: true
        label: Subtitle Color
        name: subtitlecolor
        required: false
        widget: color
      - label: Image
        name: image
        widget: image
      - label: Image Alt
        name: image_alt
        widget: string
      - label: Image Position
        name: image_position
        options:
        - left
        - right
        widget: select
      - label: Align
        name: align
        options:
        - left
        - center
        - right
        widget: select
      - fields:
        - label: Label
          name: label
          widget: string
        - label: URL
          name: url
          widget: string
        - label: Style
          name: style
          options:
          - primary
          - secondary
          widget: select
        label: Actions
        name: actions
        widget: list
      - fields:
        - allowInput: true
          enableAlpha: true
          label: Background Color
          name: background_color
          widget: color
        - label: Background Image
          name: background_image
          required: false
          widget: image
        - label: Background Image Opacity
          max: 100
          min: 0
          name: background_image_opacity
          value_type: int
          widget: number
        - label: Background Image Size
          name: background_image_size
          options:
          - cover
          - contain
          required: false
          widget: select
        - label: Background Image Repeat
          name: background_image_repeat
          options:
          - no-repeat
          - repeat
          required: false
          widget: select
        label: Background
        name: background
        widget: object
      - default: false
        label: Has Background
        name: has_background
        widget: boolean
      label: Hero Section
      name: HeroSection
      summary: '{{fields.title}} - {{fields.subtitle}}'
      widget: object
    widget: list
  folder: content/advanced
  label: Advanced Pages
  name: advanced
  preview_path: '{{slug}}'
local_backend: true
media_folder: /assets/images
media_library:
  config:
    api_key: 956814941626765
    cloud_name: dklongley
  name: cloudinary
public_folder: /images
publish_mode: editorial_workflow
